### PR TITLE
Fixing #48

### PR DESCRIPTION
**Pull request by Inujel**
Applied fix proposed in https://github.com/4teamwork/docxcompose/issues/48

### CODE REVIEW

**Review by deiferni — CHANGES_REQUESTED** [review]
Hi @Inujel, thanks for your contribution and sorry for the late response.
Could you also provide a test-case for this issue? This would help us documenting the problem and evaluating consequences of this change. Also it will guard against regressions in case it gets merged.
Thank you 💛 .

**Comment by Inujel** [comment]
Hi @deiferni ,
I had the problem when merging a docx created from a template of my company with a docx generated with pandoc. I can reproduce the problem but both of these files contain sensitive information. And when I remove their content, the problem goes away.
I'll try again asap and I let you know if I manage to reproduce the problem with a minimal pair of files.

**Comment by deiferni** [comment]
Ok. A hint: maybe you'll be able to create a broken file by unzipping the word and editing the xml directly

**Comment by nonprofittechy** [comment]
Coming in much later but running into this same issue trying to use `docxcompose` inside jhpyle/docassemble.

see https://github.com/LemmaLegalConsulting/docassemble-tclpgoogledocsmerger/issues/3. where does this PR stand? Any intention to address the problem a different way? I can likely get some test DOCX files to reproduce it. Editing/resaving the DOCX might not be feasible long term for this use case.

**Comment by nonprofittechy** [comment]
This attached test file does not contain sensitive information, in case that is helpful. Also uploading after resaving in Word--which does fix the issue as a one-off.

[doc_5_resaved.docx](https://github.com/4teamwork/docxcompose/files/7678693/doc_5_resaved.docx)
[doc_5.docx](https://github.com/4teamwork/docxcompose/files/7678694/doc_5.docx)

**Comment by njohner** [comment]
Superseded by https://github.com/4teamwork/docxcompose/pull/80

**Pull request closed without merging**
