### PR TITLE
Composer.add_styles checks if styles are none

### LINKED ISSUE #48: Composer.add_styles fails to check duplicated element is not None
Calling `Composer.insert` was throwing the following error:
```plain
...
  File ".../docxcompose/composer.py", line 71, in insert
    self.add_styles(doc, element)
  File ".../docxcompose/composer.py", line 253, in add_styles
    self.doc.styles.element.append(style_element)
TypeError: Argument 'element' has incorrect type (expected lxml.etree._Element, got NoneType)
```

Worked around by checking for None:
```diff
--- composer.py.bak     2020-01-30 16:40:16.344303674 +0000
+++ composer.py 2020-01-30 16:40:51.412775183 +0000
@@ -250,18 +250,19 @@
             our_style_id = self.mapped_style_id(style_id)
             if our_style_id not in our_style_ids:
                 style_element = deepcopy(doc.styles.element.get_by_id(style_id))
-                self.doc.styles.element.append(style_element)
-                self.add_numberings(doc, style_element)
-                # Also add linked styles
-                linked_style_ids = xpath(style_element, './/w:link/@w:val')
-                if linked_style_ids:
-                    linked_style_id = linked_style_ids[0]
-                    our_linked_style_id = self.mapped_style_id(linked_style_id)
-                    if our_linked_style_id not in our_style_ids:
-                        our_linked_style = doc.styles.element.get_by_id(
-                            linked_style_id)
-                        self.doc.styles.element.append(deepcopy(
-                            our_linked_style))
+                if style_element is not None:
+                    self.doc.styles.element.append(style_element)
+                    self.add_numberings(doc, style_element)
+                    # Also add linked styles
+                    linked_style_ids = xpath(style_element, './/w:link/@w:val')
+                    if linked_style_ids:
+                        linked_style_id = linked_style_ids[0]
+                        our_linked_style_id = self.mapped_style_id(linked_style_id)
+                        if our_linked_style_id not in our_style_ids:
+                            our_linked_style = doc.styles.element.get_by_id(
+                                linked_style_id)
+                            self.doc.styles.element.append(deepcopy(
+                                our_linked_style))
             else:
                 # Create a mapping for abstractNumIds used in existing styles
                 # This is used when adding numberings to avoid having multiple
```

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Fixes #48, another attempt of #58 and #64, but this time with a working test document that we have permission to make public.

 If you remove the fix applied in the first commit but keep the new test, that test will fail with the below:
 ```log
___________________________________ test_continue_when_no_styles ____________________________________

    def test_continue_when_no_styles():
        """Expects not to throw a type error"""
>       doc = ComposedDocument("aatmay.docx", "aatmay.docx")

tests/test_styles.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:104: in __init__
    composer.append(Document(docx_path(filename)))
docxcompose/composer.py:51: in append
    self.insert(index, doc, remove_property_fields=remove_property_fields)
docxcompose/composer.py:81: in insert
    self.add_styles_from_other_parts(doc)
docxcompose/composer.py:264: in add_styles_from_other_parts
    self.add_styles(doc, el)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <docxcompose.composer.Composer object at 0x7fb8705cf7c0>
doc = <docx.document.Document object at 0x7fb87060a880>
element = <Element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}footnotes at 0x7fb87067b640>

    def add_styles(self, doc, element):
        """Add styles from the given document used in the given element."""
        our_style_ids = [s.style_id for s in self.doc.styles]
        # de-duplicate ids and keep order to make sure tests are not flaky
        used_style_ids = list(OrderedDict.fromkeys([e.val for e in xpath(
            element, './/w:tblStyle|.//w:pStyle|.//w:rStyle')]))
    
        for style_id in used_style_ids:
            our_style_id = self.mapped_style_id(style_id)
            if our_style_id not in our_style_ids:
                style_element = deepcopy(doc.styles.element.get_by_id(style_id))
>               self.doc.styles.element.append(style_element)
E               TypeError: Argument 'element' has incorrect type (expected lxml.etree._Element, got NoneType)
```
Let me know if there's anything else that would help get this merged.

### CODE REVIEW

**Comment by seasick** [comment]
Hi @buchi, is this PR something which we can expect to end up in a new release soon?

**Comment by JonZeolla** [comment]
@buchi / @lukasgraf / @4teamwork this PR fixes an issue I'm currently encountering.  Can you please take a look?

**Review by njohner — APPROVED** [review]
LGTM

**Comment by njohner** [comment]
And sorry for the delay, I saw the PR just now by chance.

**Pull request merged**
